# Generated by Django 3.2.5 on 2023-05-01 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Adresse Email')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=40, verbose_name='Prenom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('mot_de_passe', models.CharField(max_length=255, verbose_name='Mot de passe')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=200)),
                ('texte', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=50, verbose_name='Identifiant')),
                ('date', models.DateField(verbose_name='Date de Notification')),
                ('heure', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Adresse Email')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=40, verbose_name='Prenom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('image', models.ImageField(blank=True, upload_to='utilisateur/')),
                ('role', models.CharField(max_length=30, verbose_name='Role')),
                ('mot_de_passe', models.CharField(max_length=255, verbose_name='Mot de passe')),
                ('administrateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.administrateur')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.utilisateur')),
                ('identifiant', models.CharField(max_length=30, verbose_name='Identifiant')),
            ],
            bases=('app.utilisateur',),
        ),
        migrations.CreateModel(
            name='Moderateur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.utilisateur')),
                ('identifiant', models.CharField(max_length=30, verbose_name='Identifiant')),
            ],
            bases=('app.utilisateur',),
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, verbose_name='nom')),
                ('theme', models.CharField(max_length=30, verbose_name='theme')),
                ('comment', models.CharField(blank=True, max_length=3000, verbose_name='comment')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur')),
                ('moderateurs', models.ManyToManyField(related_name='moderateur', to='app.Moderateur')),
            ],
        ),
    ]
